spring:
    datasource:
        hikari:
            jdbc-url: jdbc:h2:tcp://localhost/~/db_practice
            username: sa
            password: ""
            maximum-pool-size: 20
    jpa:
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: create-drop
            
domain:
    allow-cors:
        localhost: http://localhost:8080

jwt:
    accessTokenSecret: "mfoa)29afas!@fdASF3e"
    refreshTokenSecret: "1892ka09vm/$@!adsf@A32v"
    accessTokenLifetime: 1800000 # 30 min
    refreshTokenLifetime: 10800000 # 3 hour

config:
    aws:
        accessKeyId: "tempAccessKeyId"
        secretAccessKey: "tempSecretAccessKey"
    async:
        asyncPoolMinCapacity: 10
        asyncPoolMaxCapacity: 50
        asyncPoolQueueCapacity: 50
    