package com.codepied.api.test

enum class DocumentEnum {
    EMAIL_SIGNUP,
    EMAIL_LOGIN,
    SOCIAL_LOGIN,
    USER_INFO_DUPLICATE,
    EMAIL_USER_PASSWORD_CHANGE,
    NICKNAME_CHANGE,
    USER_INTEGRATION,
    RETRIEVE_USER_INTEGRATIONS,
    ;
}